---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: scrumblr-app             # Unique name of the Kubernetes resource
spec:
  replicas: 1               # Number of pods to run at any given time
  selector:
    matchLabels:
      app: scrumblr-app          # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: scrumblr-app 
    spec:
      containers:
      - name: scrumblr-app
        image: 774013277495.dkr.ecr.us-east-1.amazonaws.com/bulk/scrumblr:latest 
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 8080  # Should match the port number that the app listen to
        env:                     # Environment variables passed to the container
          - name: REDIS_HOST
            value: redis-master
          - name: REDIS_PORT
            value: "6379"    
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: scrumblr-app-service     # Unique name of the resource
spec:              # Expose the Pods by opening a port on each Node and proxying it to the service.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - port: 8080
  selector:
    app: scrumblr-app
